-- Execute this in your Supabase SQL Editor

-- Table: scrapper_accounts
create table if not exists public.scrapper_accounts (
  id uuid not null default gen_random_uuid (),
  username text not null,
  password_encrypted text null,
  is_active boolean null default true,
  last_login timestamp with time zone null,
  session_cookies jsonb null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint scrapper_accounts_pkey primary key (id),
  constraint scrapper_accounts_username_key unique (username)
);

-- Table: users_scrapping
create table if not exists public.users_scrapping (
  id bigint generated by default as identity,
  user text not null,
  status text null,
  data_ultimo_scrapping timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint users_scrapping_pkey primary key (id),
  constraint users_scrapping_user_key unique (user) -- Ensure username is unique in target list
);

-- Table: scrappers_contents
create table if not exists public.scrappers_contents (
  id uuid not null default gen_random_uuid (),
  username text not null,
  postid text not null,
  posturl text null,
  mediatype text null,
  alttext text null,
  mediaurl text null,
  videourl text null,
  iscarousel boolean null,
  carouselimages jsonb null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint scrappers_contents_pkey primary key (id),
  constraint scrappers_contents_postid_key unique (postid) -- CRITICAL: Unique constraint on postid to prevent duplicates
);

-- Indices
create index if not exists idx_scrapper_accounts_username on public.scrapper_accounts (username);
create index if not exists idx_scrapper_accounts_is_active on public.scrapper_accounts (is_active);
create index if not exists idx_users_scrapping_status on public.users_scrapping (status);
create index if not exists idx_scrappers_contents_username on public.scrappers_contents (username);
create index if not exists idx_scrappers_contents_postid on public.scrappers_contents (postid);

-- Trigger for updated_at (reusable)
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_scrapper_accounts_updated_at
    before update on public.scrapper_accounts
    for each row
    execute procedure update_updated_at_column();
