-- Execute this in your Supabase SQL Editor

-- Table: scrapper_accounts
create table if not exists public.scrapper_accounts (
  id uuid not null default gen_random_uuid (),
  username text not null,
  password_encrypted text null,
  is_active boolean null default true,
  last_login timestamp with time zone null,
  session_cookies jsonb null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint scrapper_accounts_pkey primary key (id),
  constraint scrapper_accounts_username_key unique (username)
);

-- Table: users_scrapping
create table if not exists public.users_scrapping (
  id bigint generated by default as identity,
  "user" text not null,
  status text null,
  data_ultimo_scrapping timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  constraint users_scrapping_pkey primary key (id),
  constraint users_scrapping_user_key unique ("user") -- Ensure username is unique in target list
);

-- Table: scrappers_contents
create table if not exists public.scrappers_contents (
  id uuid not null default gen_random_uuid (),
  username text not null,
  postid text not null,
  posturl text null,
  mediatype text null,
  alttext text null,
  mediaurl text null,
  videourl text null,
  iscarousel boolean null,
  carouselimages jsonb null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint scrappers_contents_pkey primary key (id),
  constraint scrappers_contents_postid_key unique (postid) -- CRITICAL: Unique constraint on postid to prevent duplicates
);

-- ============================================================
-- MIGRATION: New tables for likes and comments extraction
-- ============================================================

-- Table: post_likes
create table if not exists public.post_likes (
  id uuid not null default gen_random_uuid (),
  postid text not null,
  liker_username text not null,
  created_at timestamp with time zone not null default now(),
  constraint post_likes_pkey primary key (id),
  constraint post_likes_postid_liker_key unique (postid, liker_username)
);

-- Table: post_comments
create table if not exists public.post_comments (
  id uuid not null default gen_random_uuid (),
  postid text not null,
  commenter_username text not null,
  comment_text text not null,
  created_at timestamp with time zone not null default now(),
  constraint post_comments_pkey primary key (id),
  constraint post_comments_postid_commenter_text_key unique (postid, commenter_username, comment_text)
);

-- ============================================================
-- MIGRATION: Profile bio and highlights extraction
-- ============================================================

-- Table: profile_bio
create table if not exists public.profile_bio (
  id uuid not null default gen_random_uuid (),
  username text not null,
  bio text not null default '',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint profile_bio_pkey primary key (id),
  constraint profile_bio_username_key unique (username)
);

-- Table: profile_highlights
create table if not exists public.profile_highlights (
  id uuid not null default gen_random_uuid (),
  username text not null,
  title text not null,
  cover_url text null,
  highlight_url text null,
  created_at timestamp with time zone not null default now(),
  constraint profile_highlights_pkey primary key (id),
  constraint profile_highlights_username_title_key unique (username, title)
);

-- Table: profile_highlight_items
create table if not exists public.profile_highlight_items (
  id uuid not null default gen_random_uuid (),
  highlight_id uuid not null references public.profile_highlights(id) on delete cascade,
  media_url text not null,
  media_type text not null default 'image',
  created_at timestamp with time zone not null default now(),
  constraint profile_highlight_items_pkey primary key (id),
  constraint profile_highlight_items_highlight_media_key unique (highlight_id, media_url)
);

-- Indices
create index if not exists idx_scrapper_accounts_username on public.scrapper_accounts (username);
create index if not exists idx_scrapper_accounts_is_active on public.scrapper_accounts (is_active);
create index if not exists idx_users_scrapping_status on public.users_scrapping (status);
create index if not exists idx_scrappers_contents_username on public.scrappers_contents (username);
create index if not exists idx_scrappers_contents_postid on public.scrappers_contents (postid);
create index if not exists idx_post_likes_postid on public.post_likes (postid);
create index if not exists idx_post_comments_postid on public.post_comments (postid);
create index if not exists idx_profile_bio_username on public.profile_bio (username);
create index if not exists idx_profile_highlights_username on public.profile_highlights (username);
create index if not exists idx_profile_highlight_items_highlight_id on public.profile_highlight_items (highlight_id);

-- Trigger for updated_at (reusable)
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_scrapper_accounts_updated_at
    before update on public.scrapper_accounts
    for each row
    execute procedure update_updated_at_column();
